### ISSUE TITLE
How to set up data properly?

### ISSUE THREAD

**Issue by jmrfox** [op3/nudel#1]
Hi, I have nudel built but it does not correctly see the ENSDF data and I would appreciate some help fixing this. 
You refer to a string 'ensdf.???' in the providers method via a call to glob.
However, my files are named following the ENSDF archives (which you link), that is ensdf_160816_099.zip , etc. , so these files are not seen. By the way, newer ENSDF files follow a different convention, with no mass numbers:  ensdf_221101.zip

What is the intended filename format?
Thanks,

**Comment by op3** [comment]
You have to unzip the ENSDF archives to either `~/.local/share/ensdf` (resulting in paths like `~/.local/share/ensdf/ensdf.208`) or to `$ENSDF_PATH`, which you have to set manually yourself.

The following two commands should be sufficient to download and extract the archive:
```
wget https://www.nndc.bnl.gov/ensdfarchivals/distributions/dist22/ensdf_221101.zip
unzip ensdf_221101.zip -d ~/.local/share/ensdf
```

Thanks for the heads up with respect to the new naming convention of the archives.

**Comment by jmrfox** [comment]
Thanks for your reply!  I got it working now. And thank you for making this tool available, it has been extremely helpful for me.
